"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Loader2, Send, X } from "lucide-react";
import toast from "react-hot-toast";
import { getCookie } from "@/lib/cookie";

const initialForm = { fullName: "", email: "", phone: "", province: "", city: "", address: "", postalCode: "", workHistory: "", artHistory: "", educationLevel: "", educationField: "", reason: "", knowsInstructors: false, familiarityDetails: "", instagramId: "", virtualPhone: "", landline: "" };
type FormData = typeof initialForm;

export default function CourseRegistrationModal({ courseId, courseTitle, onClose, onSuccess }: { courseId: string; courseTitle: string; onClose: () => void; onSuccess: (profileUpdated: boolean) => void }) {
  const [form, setForm] = useState<FormData>(initialForm);
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { document.body.style.overflow = "hidden"; const token = getCookie("token"); fetch("/api/user/profile", { headers: { authorization: `Bearer ${token || ""}` } }).then((response) => response.json()).then(({ user }) => { if (user) setForm({ fullName: user.name || "", email: user.email || "", phone: user.phone || "", province: user.province || "", city: user.city || "", address: user.address || "", postalCode: user.postalCode || "", workHistory: user.workHistory || "", artHistory: user.artHistory || "", educationLevel: user.educationLevel || "", educationField: user.educationField || "", reason: "", knowsInstructors: false, familiarityDetails: "", instagramId: user.instagramId || "", virtualPhone: user.virtualPhone || user.phone || "", landline: user.landline || "" }); }).finally(() => setLoading(false)); return () => { document.body.style.overflow = ""; }; }, []);
  function update<K extends keyof FormData>(key: K, value: FormData[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function validateStep() { const fields = step === 1 ? ["fullName", "email", "phone", "province", "city", "address", "postalCode"] : step === 2 ? ["educationLevel", "educationField"] : ["reason", "virtualPhone"]; const missing = fields.some((key) => !String(form[key as keyof FormData]).trim()); if (missing) { toast.error("لطفاً تمام فیلدهای الزامی این مرحله را تکمیل کنید"); return false; } if (step === 3 && form.knowsInstructors && !form.familiarityDetails.trim()) { toast.error("محل آشنایی با اساتید را بنویسید"); return false; } return true; }
  async function submit() { if (!validateStep()) return; setSaving(true); try { const response = await fetch("/api/course-applications", { method: "POST", headers: { "Content-Type": "application/json", authorization: `Bearer ${getCookie("token") || ""}` }, body: JSON.stringify({ ...form, courseId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "خطا در ارسال فرم"); onSuccess(Boolean(data.profileUpdated)); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا در ارسال فرم"); } finally { setSaving(false); } }
  const inputClass = "mt-1.5 w-full px-4 py-3 rounded-xl border border-surface-variant bg-white text-sm outline-none focus:ring-2 focus:ring-secondary-fixed";
  return <div className="fixed inset-0 z-[100] bg-primary/75 backdrop-blur-lg p-3 md:p-6 overflow-y-auto" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose(); }}><div className="max-w-3xl mx-auto bg-[#fbf8ff] rounded-[2rem] overflow-hidden shadow-2xl animate-fade-in-up"><div className="bg-primary text-white p-6 flex justify-between gap-4"><div><p className="text-xs text-secondary-fixed font-bold">فرم درخواست ثبت‌نام</p><h2 className="font-black text-xl mt-1">{courseTitle}</h2></div><button onClick={onClose} disabled={saving}><X size={21} /></button></div><div className="px-6 md:px-8 pt-6"><div className="flex items-center gap-2">{[1, 2, 3].map((number) => <div key={number} className="flex-1"><div className={`h-1.5 rounded-full ${number <= step ? "bg-secondary" : "bg-surface-variant"}`} /><p className={`text-[10px] mt-1 ${number === step ? "text-primary font-bold" : "text-outline"}`}>مرحله {number.toLocaleString("fa-IR")}</p></div>)}</div></div>
    <div className="p-6 md:p-8">{loading ? <div className="py-20 flex justify-center"><Loader2 className="animate-spin text-primary" /></div> : <>
      {step === 1 && <div className="grid md:grid-cols-2 gap-4"><div className="md:col-span-2 rounded-xl bg-secondary-fixed/30 text-secondary p-3 text-xs leading-6">نام، ایمیل و موبایل از حساب شما دریافت شده‌اند. اگر آن‌ها را تغییر دهید، پروفایل حساب کاربری نیز بروزرسانی خواهد شد.</div>{[{ key: "fullName", label: "نام و نام خانوادگی *", type: "text" }, { key: "phone", label: "شماره تلفن همراه *", type: "tel" }, { key: "email", label: "ایمیل *", type: "email" }, { key: "province", label: "استان *", type: "text" }, { key: "city", label: "شهر *", type: "text" }, { key: "postalCode", label: "کد پستی *", type: "text" }].map((item) => <label key={item.key} className="text-sm font-bold text-primary">{item.label}<input type={item.type} value={String(form[item.key as keyof FormData])} onChange={(event) => update(item.key as keyof FormData, event.target.value as never)} className={inputClass} /></label>)}<label className="md:col-span-2 text-sm font-bold text-primary">آدرس محل سکونت *<textarea rows={3} value={form.address} onChange={(event) => update("address", event.target.value)} className={inputClass} /></label></div>}
      {step === 2 && <div className="space-y-4"><div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-bold text-primary">مقطع تحصیلی *<input value={form.educationLevel} onChange={(event) => update("educationLevel", event.target.value)} placeholder="مثال: کارشناسی" className={inputClass} /></label><label className="text-sm font-bold text-primary">رشته تحصیلی *<input value={form.educationField} onChange={(event) => update("educationField", event.target.value)} className={inputClass} /></label></div><label className="block text-sm font-bold text-primary">سوابق کاری<textarea rows={4} value={form.workHistory} onChange={(event) => update("workHistory", event.target.value)} className={inputClass} /></label><label className="block text-sm font-bold text-primary">سوابق هنری<textarea rows={4} value={form.artHistory} onChange={(event) => update("artHistory", event.target.value)} className={inputClass} /></label></div>}
      {step === 3 && <div className="space-y-4"><label className="block text-sm font-bold text-primary">دلیل انتخاب این دوره *<textarea rows={4} value={form.reason} onChange={(event) => update("reason", event.target.value)} className={inputClass} /></label><div className="rounded-xl border border-surface-variant bg-white p-4"><p className="text-sm font-bold text-primary">آیا از قبل با اساتید این دوره آشنایی دارید؟</p><div className="flex gap-5 mt-3"><label className="flex gap-2 text-sm"><input type="radio" checked={form.knowsInstructors} onChange={() => update("knowsInstructors", true)} />بله</label><label className="flex gap-2 text-sm"><input type="radio" checked={!form.knowsInstructors} onChange={() => { update("knowsInstructors", false); update("familiarityDetails", ""); }} />خیر</label></div>{form.knowsInstructors && <label className="block text-sm font-bold text-primary mt-4">کجا با ایشان آشنا شده‌اید؟ *<input value={form.familiarityDetails} onChange={(event) => update("familiarityDetails", event.target.value)} className={inputClass} /></label>}</div><div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-bold text-primary">آیدی اینستاگرام<input value={form.instagramId} onChange={(event) => update("instagramId", event.target.value)} className={inputClass} dir="ltr" /></label><label className="text-sm font-bold text-primary">شماره فعال در فضای مجازی *<input value={form.virtualPhone} onChange={(event) => update("virtualPhone", event.target.value)} className={inputClass} dir="ltr" /></label><label className="text-sm font-bold text-primary">شماره تلفن ثابت<input value={form.landline} onChange={(event) => update("landline", event.target.value)} className={inputClass} dir="ltr" /></label></div></div>}
      <div className="flex justify-between gap-3 mt-7 pt-5 border-t border-surface-variant"><button type="button" onClick={() => step === 1 ? onClose() : setStep((current) => current - 1)} disabled={saving} className="flex items-center gap-2 px-5 py-2.5 rounded-xl border border-surface-variant text-sm text-outline"><ArrowRight size={16} />{step === 1 ? "انصراف" : "مرحله قبل"}</button>{step < 3 ? <button type="button" onClick={() => { if (validateStep()) setStep((current) => current + 1); }} className="flex items-center gap-2 bg-primary text-white px-6 py-2.5 rounded-xl text-sm font-bold">ادامه<ArrowLeft size={16} /></button> : <button type="button" onClick={submit} disabled={saving} className="flex items-center gap-2 bg-primary text-white px-6 py-2.5 rounded-xl text-sm font-bold disabled:opacity-50">{saving ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}ارسال درخواست</button>}</div>
    </>}</div></div></div>;
}
