import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Imam Ruhollah School",
  description: "Privacy Policy for Imam Ruhollah School and optional Google Sign-In.",
};

export default function PrivacyPolicyPage() {
  return <main className="min-h-screen bg-surface pt-28 pb-20" dir="ltr"><article className="mx-auto max-w-4xl px-5 md:px-8"><div className="rounded-[2rem] border border-outline-variant/40 bg-white p-7 shadow-sm md:p-12"><p className="text-sm font-bold tracking-[.18em] text-secondary">LEGAL</p><h1 className="mt-4 text-4xl font-black text-primary">Privacy Policy</h1><p className="mt-3 text-sm text-outline">Last updated: July 31, 2026</p><div className="mt-10 space-y-8 text-[15px] leading-8 text-on-background/80"><section><h2 className="text-xl font-black text-primary">Imam Ruhollah School</h2><p className="mt-3">Imam Ruhollah School is an arts and media learning platform. This Privacy Policy explains how we collect and use information to provide course registration, educational services, student accounts, and optional Google Sign-In.</p></section><section><h2 className="text-xl font-black text-primary">Information We Collect</h2><p className="mt-3">When you create an account using email and password, we collect the information you provide, such as your name and email address. When you choose optional Google Sign-In, we receive your verified Google email address, profile name, and profile image.</p></section><section><h2 className="text-xl font-black text-primary">How We Use Information</h2><p className="mt-3">We use this information only to create and secure your account, provide access to educational services, communicate about your account, and improve the learning experience. Google Sign-In information is not used for advertising or sold to third parties.</p></section><section><h2 className="text-xl font-black text-primary">Google Sign-In</h2><p className="mt-3">Google Sign-In is optional. Users may use email and password instead. We request only basic profile and email information needed for authentication. You can stop using Google Sign-In at any time by using your account password or contacting us.</p></section><section><h2 className="text-xl font-black text-primary">Data Protection and Contact</h2><p className="mt-3">We take reasonable measures to protect account information. For questions about this policy or your information, contact us through the official <Link href="/about#contact" className="font-bold text-secondary underline">contact page</Link>.</p></section></div><div className="mt-10 border-t border-surface-variant pt-6"><Link href="/google-oauth" className="font-bold text-secondary">Google Sign-In information</Link></div></div></article></main>;
}
