export const APP_VERSION = "2.0.0";

export interface ReleaseNote {
  id: string;
  title: string;
  summary: string;
  publishedAt: string;
  version?: string;
  type: "release" | "feature" | "improvement" | "fix";
}

const unsortedReleaseNotes: ReleaseNote[] = [
  {
    id: "public-privacy-policy-page",
    title: "صفحه عمومی حریم خصوصی",
    summary: "سیاست حفظ حریم خصوصی به‌صورت عمومی اضافه و فقط از صفحه درباره ما و تماس با ما در دسترس قرار گرفت.",
    publishedAt: "2026-07-31T03:30:00+03:30",
    type: "feature",
  },
  {
    id: "remove-temporary-oauth-branding-pages",
    title: "حذف صفحات موقت Branding گوگل",
    summary: "صفحه‌های معرفی و حریم خصوصی موقت OAuth از سایت حذف شدند؛ ورود اختیاری با گوگل باقی مانده است.",
    publishedAt: "2026-07-31T03:15:00+03:30",
    type: "fix",
  },
  {
    id: "unique-google-oauth-brand-identity",
    title: "هویت یکتای Branding گوگل",
    summary: "نام انگلیسی یکتای آکادمی و لوگوی رسمی آن در صفحه OAuth برای تطابق با Consent Screen اضافه شد.",
    publishedAt: "2026-07-31T03:00:00+03:30",
    type: "fix",
  },
  {
    id: "public-privacy-policy-for-google-oauth",
    title: "حریم خصوصی عمومی برای OAuth گوگل",
    summary: "Privacy Policy عمومی روی دامنه اصلی ایجاد و از صفحه معرفی OAuth و فوتر قابل دسترس شد.",
    publishedAt: "2026-07-31T02:45:00+03:30",
    type: "feature",
  },
  {
    id: "root-home-english-oauth-branding",
    title: "هویت انگلیسی OAuth در صفحه اصلی",
    summary: "نام و هدف رسمی انگلیسی Imam Ruhollah School در خود صفحه اصلی نیز درج شد تا بررسی Branding گوگل آن را شناسایی کند.",
    publishedAt: "2026-07-31T02:30:00+03:30",
    type: "fix",
  },
  {
    id: "english-google-oauth-branding-page",
    title: "صفحه انگلیسی معرفی OAuth گوگل",
    summary: "صفحه مستقل انگلیسی برای معرفی نام برنامه، هدف ورود گوگل، داده‌های دریافت‌شده و اختیاری‌بودن آن اضافه شد.",
    publishedAt: "2026-07-31T02:15:00+03:30",
    type: "improvement",
  },
  {
    id: "google-oauth-purpose-disclosure",
    title: "شفاف‌سازی هدف ورود گوگل",
    summary: "هدف سامانه و استفاده اختیاری از ورود گوگل، داده‌های دریافت‌شده و کاربرد آن‌ها به‌صورت صریح در صفحه اصلی درج شد.",
    publishedAt: "2026-07-31T02:00:00+03:30",
    type: "improvement",
  },
  {
    id: "oauth-branding-home-purpose",
    title: "شفاف‌سازی هویت آکادمی در صفحه اصلی",
    summary: "نام رسمی آکادمی و هدف سامانه به‌صورت ثابت و قابل‌خواندن در صفحه اصلی اضافه شد تا شرایط Branding گوگل رعایت شود.",
    publishedAt: "2026-07-31T01:45:00+03:30",
    type: "improvement",
  },
  {
    id: "google-oauth-login",
    title: "ورود و ثبت‌نام با گوگل",
    summary: "ورود امن Google OAuth با اتصال حساب‌ها از طریق ایمیل تأییدشده و دکمه‌های ورود در فرم‌های سایت اضافه شد.",
    publishedAt: "2026-07-31T01:30:00+03:30",
    type: "feature",
  },
  {
    id: "google-indexing-sitemap-and-robots",
    title: "آماده‌سازی ایندکس گوگل",
    summary: "robots.txt و Sitemap پویا برای صفحه‌های عمومی، دوره‌ها، رویدادها، خبرها و گالری اضافه شد.",
    publishedAt: "2026-07-30T11:25:00+03:30",
    type: "improvement",
  },
  {
    id: "attach-existing-courses-to-collection",
    title: "اتصال دوره‌های قبلی به مجموعه جامع",
    summary: "از داخل دوره جامع می‌توان دوره‌های مستقل قبلی را انتخاب و به زیر‌دوره مجموعه تبدیل کرد.",
    publishedAt: "2026-07-30T11:10:00+03:30",
    type: "improvement",
  },
  {
    id: "add-child-courses-from-parent",
    title: "افزودن زیر‌دوره از مجموعه جامع",
    summary: "مدیر می‌تواند هنگام ویرایش دوره جامع، زیر‌دوره جدید بسازد یا زیر‌دوره‌های متصل را مستقیم ویرایش کند.",
    publishedAt: "2026-07-30T10:55:00+03:30",
    type: "improvement",
  },
  {
    id: "comprehensive-course-collection-experience",
    title: "تکمیل تجربه مجموعه‌های جامع",
    summary: "دوره جامع به صفحه معرفی زیر‌دوره‌ها تبدیل شد و هر زیر‌دوره با زمان، قیمت و اقدام ثبت‌نام مستقل نمایش داده می‌شود.",
    publishedAt: "2026-07-30T10:40:00+03:30",
    type: "feature",
  },
  {
    id: "two-line-admin-content-urls",
    title: "نمایش دوخطی آدرس محتوا",
    summary: "مسیر ثابت و slug قابل‌ویرایش در فرم‌های محتوا برای خوانایی بهتر در دو خط نمایش داده می‌شوند.",
    publishedAt: "2026-07-30T10:25:00+03:30",
    type: "improvement",
  },
  {
    id: "admin-content-link-controls",
    title: "کنترل لینک در فهرست مدیریت محتوا",
    summary: "آیکن کپی لینک کنار مداد و حذف دوره‌ها، رویدادها و گالری اضافه و جهت نمایش آدرس فرم‌ها اصلاح شد.",
    publishedAt: "2026-07-30T10:10:00+03:30",
    type: "improvement",
  },
  {
    id: "content-permalink-copy-controls",
    title: "آدرس‌های خوانا و کپی لینک محتوا",
    summary: "لینک یکتای دوره، رویداد، خبر و گالری با دکمه زنجیر در کنار عنوان برای کپی سریع اضافه شد.",
    publishedAt: "2026-07-30T09:50:00+03:30",
    type: "improvement",
  },
  {
    id: "animated-global-error-pages",
    title: "صفحات خطای اختصاصی و متحرک",
    summary: "صفحات ۴۰۴، خطای صفحه و خطای سراسری با طراحی وکتور و مسیرهای بازیابی اختصاصی اضافه شدند.",
    publishedAt: "2026-07-30T09:30:00+03:30",
    type: "feature",
  },
  {
    id: "restore-newsletter-section-order",
    title: "بازگردانی جایگاه خبرنامه",
    summary: "بخش خبرنامه به ترتیب قبلی صفحه و جایگاه خود در انتهای محتوای اصلی بازگردانده شد.",
    publishedAt: "2026-07-30T09:15:00+03:30",
    type: "fix",
  },
  {
    id: "interactive-home-course-button",
    title: "دکمه تعاملی کارت دوره‌ها",
    summary: "دکمه مشاهده صفحه دوره و ثبت‌نام در صفحه اصلی به‌صورت تعاملی و در مرکز پایین کارت دوره بازطراحی شد.",
    publishedAt: "2026-07-30T09:00:00+03:30",
    type: "improvement",
  },
  {
    id: "welcome-newsletter-admin-email-tools",
    title: "تجربه ایمیل و خبرنامه آکادمی",
    summary: "قالب‌های گرافیکی تأیید و خوش‌آمدگویی، دعوت هوشمند ثبت‌نام، عضویت خبرنامه در پروفایل و ابزار ارسال ایمیل مدیریت اضافه شد.",
    publishedAt: "2026-07-30T08:30:00+03:30",
    type: "feature",
  },
  {
    id: "about-contact-page-and-footer-address",
    title: "صفحه درباره آکادمی و تماس با ما",
    summary: "صفحه اختصاصی معرفی و تماس، آدرس کامل زیر نقشه و چیدمان جدید لوگوی فوتر اضافه شد.",
    publishedAt: "2026-07-30T08:00:00+03:30",
    type: "feature",
  },
  {
    id: "footer-social-icons-and-font-weights",
    title: "بهبود وزن فونت‌ها و شبکه‌های اجتماعی فوتر",
    summary: "وزن مناسب خانواده فونت‌ها برای تیترها اعمال شد و لینک‌های اینستاگرام و بله با لوگو زیر معرفی آکادمی قرار گرفتند.",
    publishedAt: "2026-07-30T07:30:00+03:30",
    type: "improvement",
  },
  {
    id: "registration-form-fields-and-course-price-visibility",
    title: "تکمیل فرم ثبت‌نام دوره‌ها",
    summary: "تاریخ تولد، سوابق و آیدی اینستاگرام به‌صورت الزامی اضافه شد، کد پستی اختیاری شد و قیمت از کارت دوره‌های صفحه اصلی حذف شد.",
    publishedAt: "2026-07-30T07:00:00+03:30",
    type: "improvement",
  },
  {
    id: "instant-auth-navbar-and-dashboard-spacing",
    title: "به‌روزرسانی آنی وضعیت ورود",
    summary: "وضعیت ورود نوار بالایی پس از ثبت‌نام یا ورود بدون رفرش به‌روزرسانی می‌شود و فاصله داشبورد از topbar اصلاح شد.",
    publishedAt: "2026-07-30T06:20:00+03:30",
    type: "improvement",
  },
  {
    id: "local-postfix-email-relay",
    title: "پشتیبانی از Mail Server محلی",
    summary: "سامانه ارسال کد تأیید با Postfix محلی روی loopback و بدون ذخیره نام کاربری یا رمز SMTP سازگار شد و STARTTLS محلی را نادیده می‌گیرد.",
    publishedAt: "2026-07-30T05:40:00+03:30",
    type: "improvement",
  },
  {
    id: "optional-email-verification",
    title: "اختیاری‌شدن تأیید ایمیل",
    summary: "تأیید ایمیل به‌صورت پیش‌فرض غیرفعال شد تا کاربران بلافاصله وارد شوند و امکان فعال‌سازی آینده با تنظیم محیطی باقی ماند.",
    publishedAt: "2026-07-30T05:31:21+03:30",
    type: "improvement",
  },
  {
    id: "email-verification-and-admin-passwords",
    title: "تأیید ایمیل و مدیریت رمز کاربران",
    summary: "ثبت‌نام ایمیلی با کد شش‌رقمی، انقضای ده‌دقیقه‌ای و ارسال مجدد امن شد و مدیر می‌تواند برای کاربران رمز عبور جدید تعیین کند.",
    publishedAt: "2026-07-30T05:27:28+03:30",
    type: "feature",
  },
  {
    id: "gallery-metadata-simplification",
    title: "ساده‌سازی اطلاعات گالری",
    summary: "عنوان و توضیحات اصلی تصویر مستقیماً برای متادیتای سئو استفاده می‌شوند و ورودی‌های تکراری سئو از فرم مدیریت حذف شدند.",
    publishedAt: "2026-07-30T05:26:00+03:30",
    type: "improvement",
  },
  {
    id: "gallery-seo-persian-dates-and-site-polish",
    title: "گالری حرفه‌ای، تاریخ شمسی و بهبود رابط سایت",
    summary: "ویرایش و سئوی تصاویر گالری، صفحه مستقل هر تصویر، تاریخ‌پیکر شمسی سراسری، آدرس‌های واقعی صفحات، مدیر مستقل ثبت‌نام، کنترل بهتر اساتید و نقشه آکادمی اضافه شد.",
    publishedAt: "2026-07-30T05:07:54+03:30",
    type: "feature",
  },
  {
    id: "partners-navigation-and-footer-map",
    title: "بازآرایی همراهان و فوتر",
    summary: "همراهان زیر تنظیمات قرار گرفتند، کلیدهای اسلایدر همراهان حذف شدند، کنترل اساتید فعال شد و بخش مجوزهای فوتر با نقشه موقعیت تهران جایگزین شد.",
    publishedAt: "2026-07-30T05:06:00+03:30",
    type: "improvement",
  },
  {
    id: "course-hierarchy-and-registration-applications",
    title: "دوره‌های جامع و فرم درخواست ثبت‌نام",
    summary: "ساختار والد و فرزند دوره‌ها، زمان‌بندی برگزاری، انتخاب خرید یا فرم ثبت‌نام، اطلاعات تکمیلی پروفایل و بررسی درخواست‌ها در پنل مدیریت اضافه شد.",
    publishedAt: "2026-07-30T04:31:30+03:30",
    type: "feature",
  },
  {
    id: "topbar-typography-logo-crop",
    title: "نمایش کامل لوگوی تایپوگرافی در topbar",
    summary: "حاشیه شفاف بزرگ فایل PNG با viewBox دقیق حذف شد تا تایپوگرافی آکادمی بزرگ‌تر و خواناتر در بالای سایت نمایش داده شود.",
    publishedAt: "2026-07-30T04:30:00+03:30",
    type: "fix",
  },
  {
    id: "new-font-library-and-ravagh",
    title: "کتابخانه فونت جدید و فونت رواق",
    summary: "مسیر فونت‌ها به پوشه font-w منتقل شد و فونت‌های دوران، ری و رواق در تنظیمات سایت آکادمی و مجله قابل انتخاب هستند.",
    publishedAt: "2026-07-30T04:04:42+03:30",
    type: "improvement",
  },
  {
    id: "magazine-font-setting",
    title: "انتخاب فونت مستقل مجله",
    summary: "انتخاب فونت کلی فران یا کی به تنظیمات مجله اضافه شد و روی تمام صفحات عمومی و پنل تحریریه اعمال می‌شود.",
    publishedAt: "2026-07-30T03:55:39+03:30",
    type: "improvement",
  },
  {
    id: "independent-magazine-platform",
    title: "استقلال سایت و پنل مجله",
    summary: "مجله روی ساب‌دامین پوسته، تنظیمات و پنل تحریریه مستقل دارد؛ حساب و اعلان‌ها مشترک مانده‌اند و مسیرهای اختصاصی آکادمی از ساب‌دامین به دامنه اصلی هدایت می‌شوند.",
    publishedAt: "2026-07-30T03:48:12+03:30",
    type: "feature",
  },
  {
    id: "academy-magazine-publishing-flow",
    title: "هویت آکادمی و تأیید انتشار روایت",
    summary: "عنوان‌های مجله به آکادمی اصلاح شد، نمایش متن فارسی بهبود یافت و پس از انتشار، صفحه موفقیت همراه لینک مستقیم روایت نمایش داده می‌شود.",
    publishedAt: "2026-07-30T03:30:27+03:30",
    type: "improvement",
  },
  {
    id: "news-site-editor-and-interactions",
    title: "تحریریه داخل مجله و موشن‌های تعاملی",
    summary: "مدیران اکنون از خود صفحه اخبار خبر منتشر می‌کنند و آرشیو و صفحه مطالعه با نور دنبال‌کننده موس، عمق سه‌بعدی و پارالاکس چندلایه واکنش نشان می‌دهند.",
    publishedAt: "2026-07-30T03:09:00+03:30",
    type: "feature",
  },
  {
    id: "news-magazine-and-global-search",
    title: "مجله خبری و جستجوی سراسری",
    summary: "بخش کامل اخبار با مدیریت انتشار، آرشیو متحرک و صفحه روایت اضافه شد و جستجوی هدر اکنون دوره‌ها، رویدادها، اساتید، هنرآموختگان و اخبار را پوشش می‌دهد.",
    publishedAt: "2026-07-30T02:50:03+03:30",
    type: "feature",
  },
  {
    id: "animated-header-search",
    title: "جستجوی متحرک بالای سایت",
    summary: "نوار جستجوی هدر با بازشدن نرم، هاله متحرک و پیشنهادهای چرخشی بازطراحی شد و جستجو مستقیماً نتایج دوره‌ها را فیلتر می‌کند.",
    publishedAt: "2026-07-30T02:33:50+03:30",
    type: "feature",
  },
  {
    id: "safe-file-renaming-and-header-logo",
    title: "تغییر نام امن فایل‌ها و لوگوی جدید هدر",
    summary: "تغییر نام انگلیسی فایل با بروزرسانی خودکار لینک‌های قبلی اضافه شد و لوگوی بالای سایت با نسخه اصلی و بدون قاب دایره‌ای جایگزین شد.",
    publishedAt: "2026-07-30T02:22:51+03:30",
    type: "feature",
  },
  {
    id: "upload-errors-and-formats",
    title: "خطاهای دقیق‌تر و فرمت‌های بیشتر آپلود",
    summary: "پیام خطاهای حجم، دسترسی و پاسخ سرور شفاف شد و فرمت‌های MKV، AVI، AAC، CSV و 7Z به فایل‌منیجر اضافه شدند.",
    publishedAt: "2026-07-30T02:09:41+03:30",
    type: "fix",
  },
  {
    id: "file-upload-progress",
    title: "نمایش پیشرفت آپلود فایل‌ها",
    summary: "فایل‌منیجر اکنون درصد واقعی، حجم ارسال‌شده و وضعیت جداگانه هر فایل را هنگام آپلود نمایش می‌دهد.",
    publishedAt: "2026-07-30T02:04:02+03:30",
    type: "improvement",
  },
  {
    id: "admin-navigation-groups",
    title: "گروه‌بندی منوی مدیریت",
    summary: "اساتید و هنرآموختگان زیرمجموعه کاربران و اسلایدر زیرمجموعه تنظیمات سایت قرار گرفتند تا ساختار پنل منسجم‌تر شود.",
    publishedAt: "2026-07-30T18:40:00+03:30",
    type: "improvement",
  },
  {
    id: "department-glow-readability",
    title: "بهبود خوانایی کارت‌های دپارتمان",
    summary: "Glow رنگی به پشت باکس‌ها منتقل شد و محتوای کارت روی زمینه سفید مات و خوانا قرار گرفت؛ رنگ‌ها نیز به طیف سرمه‌ای و طلایی محدود شدند.",
    publishedAt: "2026-07-30T18:30:00+03:30",
    type: "fix",
  },
  {
    id: "department-glow-effect",
    title: "افکت نورپردازی دپارتمان‌ها",
    summary: "نوار گرادینت کارت‌های دپارتمان حذف و با Glow متحرک سرمه‌ای و طلایی در تمام لبه‌های کارت جایگزین شد.",
    publishedAt: "2026-07-30T18:20:00+03:30",
    type: "improvement",
  },
  {
    id: "version-2",
    title: "ارتقای سامانه به نسخه ۲",
    summary: "نسخه دوم سامانه با مدیریت یکپارچه صفحه اصلی، کاربران، رسانه‌ها و تجربه کاربری بهبودیافته منتشر شد.",
    publishedAt: "2026-07-30T18:00:00+03:30",
    version: APP_VERSION,
    type: "release",
  },
  {
    id: "image-editor",
    title: "ادیتور سبک تصاویر",
    summary: "کراپ، زوم و چرخش تصویر متناسب با قاب هر بخش به ورودی‌های تصویری پنل افزوده شد.",
    publishedAt: "2026-07-30T17:50:00+03:30",
    type: "feature",
  },
  {
    id: "homepage-carousels",
    title: "بازطراحی اسلایدرهای صفحه اصلی",
    summary: "نمایش دپارتمان‌ها، اساتید، همراهان و گالری برای حرکت روان، لوپ کامل و استفاده بهتر از فضا بازطراحی شد.",
    publishedAt: "2026-07-30T17:40:00+03:30",
    type: "improvement",
  },
  {
    id: "file-manager",
    title: "مدیریت فایل‌های سامانه",
    summary: "فایل‌منیجر با نمایش فضای دیسک، پیش‌نمایش، جستجو، آپلود چندفایلی و حذف امن فایل‌ها اضافه شد.",
    publishedAt: "2026-07-30T16:30:00+03:30",
    type: "feature",
  },
  {
    id: "course-categories",
    title: "دسته‌بندی‌های جدید دوره‌ها",
    summary: "۱۴ دسته‌بندی اصلی با آیکون‌های هماهنگ تعریف و فرم دوره‌ها به دسته‌های واقعی دیتابیس متصل شد.",
    publishedAt: "2026-07-30T15:20:00+03:30",
    type: "improvement",
  },
  {
    id: "profiles-and-settings",
    title: "تنظیمات یکپارچه و پروفایل عمومی",
    summary: "ویرایش محتوای صفحه اصلی، حریم خصوصی هنرجویان و پروفایل‌های اختصاصی استاد و هنرآموخته تکمیل شد.",
    publishedAt: "2026-07-30T14:00:00+03:30",
    type: "feature",
  },
];

export const releaseNotes = unsortedReleaseNotes.sort(
  (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime(),
);
