"use client";

import { Fragment, useEffect, useState } from "react";
import { Check, ClipboardList, Eye, FileCog, Loader2, Search, X } from "lucide-react";
import Link from "next/link";
import toast from "react-hot-toast";
import { getCookie } from "@/lib/cookie";
import ExportActions from "@/components/admin/export-actions";

interface Application {
  id: string; status: string; fullName: string; email: string; phone: string; nationalCode: string | null; province: string; city: string; address: string; postalCode: string;
  workHistory: string | null; artHistory: string | null; educationLevel: string; educationField: string; reason: string; knowsInstructors: boolean;
  familiarityDetails: string | null; instagramId: string | null; virtualPhone: string; landline: string | null; customResponses?: string | null; formSchema?: string | null; createdAt: string;
  discountCode?: string | null; discountLabel?: string | null; discountPercent?: number; finalAmountTomans?: number; discountDocumentUrl?: string | null;
  course: { id: string; title: string; slug: string; startDate: string | null }; user: { id: string; name: string; email: string; phone: string | null };
}
const statusLabels: Record<string, string> = { pending: "در انتظار بررسی", pending_payment: "در انتظار بررسی", approved: "تأیید شده", rejected: "رد شده" };

export default function AdminApplicationsPage() {
  const [applications, setApplications] = useState<Application[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const [courseFilter, setCourseFilter] = useState("all");
  const [selected, setSelected] = useState<Application | null>(null);
  const [saving, setSaving] = useState(false);
  const token = () => getCookie("token") || "";
  async function load() { setLoading(true); try { const response = await fetch("/api/course-applications?admin=1", { headers: { authorization: `Bearer ${token()}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setApplications(data.applications || []); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا در دریافت درخواست‌ها"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function changeStatus(status: string) { if (!selected) return; setSaving(true); try { const response = await fetch(`/api/course-applications/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json", authorization: `Bearer ${token()}` }, body: JSON.stringify({ status }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success(status === "approved" ? "درخواست تأیید و کاربر در دوره ثبت شد" : "وضعیت درخواست بروزرسانی شد"); setSelected(null); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "خطا در بروزرسانی"); } finally { setSaving(false); } }
  const courseOptions = Array.from(new Map(applications.map((item) => [item.course.id, item.course.title])).values()).sort((a, b) => a.localeCompare(b));
  const visible = applications.filter((item) => (filter === "all" || (filter === "pending" ? ["pending", "pending_payment"].includes(item.status) : item.status === filter)) && (courseFilter === "all" || item.course.id === courseFilter) && (item.fullName.includes(search) || item.email.includes(search) || item.phone.includes(search) || item.course.title.includes(search)));
  const grouped = Array.from(new Map(visible.map((item) => [item.course.id, item.course.title])).entries());
  const fields = selected ? [["نام و نام خانوادگی", selected.fullName], ["کد ملی", selected.nationalCode || "—"], ["تخفیف", selected.discountLabel ? `${selected.discountLabel} (${selected.discountPercent}٪) — مبلغ نهایی: ${(selected.finalAmountTomans || 0).toLocaleString("fa-IR")} تومان` : "بدون تخفیف"], ["ایمیل", selected.email], ["موبایل", selected.phone], ["استان و شهر", `${selected.province}، ${selected.city}`], ["آدرس", selected.address], ["کد پستی", selected.postalCode], ["مقطع و رشته", `${selected.educationLevel}، ${selected.educationField}`], ["شماره فضای مجازی", selected.virtualPhone], ["تلفن ثابت", selected.landline || "—"], ["اینستاگرام", selected.instagramId || "—"], ["سوابق کاری", selected.workHistory || "—"], ["سوابق هنری", selected.artHistory || "—"], ["دلیل انتخاب دوره", selected.reason], ["آشنایی قبلی با اساتید", selected.knowsInstructors ? `بله؛ ${selected.familiarityDetails}` : "خیر"], ...(() => { try { const responses = JSON.parse(selected.customResponses || "{}"); const schema = JSON.parse(selected.formSchema || "{}"); return (schema.steps || []).flatMap((step: { fields?: Array<{ key: string; label: string; system?: boolean }> }) => (step.fields || []).filter((field) => !field.system && responses[field.key]).map((field) => [field.label, responses[field.key]])); } catch { return []; } })()] : [];
  return <div className="space-y-5"><div className="flex flex-col gap-3"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-black text-primary">درخواست‌های ثبت‌نام</h1><div className="flex flex-wrap gap-2"><Link href="/admin/applications/form" className="inline-flex items-center gap-2 rounded-xl border border-primary/20 bg-white px-4 py-2.5 text-sm font-bold text-primary"><FileCog size={16} />فرم ثبت‌نام</Link><ExportActions endpoint="/api/admin/exports/applications" title="گزارش درخواست‌های ثبت‌نام" fileName="گزارش-درخواست‌های-ثبت‌نام" /></div></div><div className="flex flex-col md:flex-row gap-3 justify-between"><div className="relative md:w-72"><Search size={17} className="absolute right-3 top-1/2 -translate-y-1/2 text-outline" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="نام، ایمیل، موبایل یا دوره..." className="w-full pr-9 pl-3 py-2.5 rounded-xl border border-surface-variant text-sm outline-none" /></div><select value={courseFilter} onChange={(event) => setCourseFilter(event.target.value)} className="rounded-xl border border-surface-variant bg-white px-3 py-2.5 text-sm text-primary outline-none"><option value="all">همه دوره‌ها</option>{courseOptions.map((title) => <option key={title} value={applications.find((item) => item.course.title === title)!.course.id}>{title}</option>)}</select><div className="flex gap-2">{[{ value: "all", label: "همه" }, { value: "pending", label: "در انتظار" }, { value: "approved", label: "تأییدشده" }, { value: "rejected", label: "ردشده" }].map((item) => <button key={item.value} onClick={() => setFilter(item.value)} className={`px-3 py-2 rounded-xl text-xs font-bold ${filter === item.value ? "bg-primary text-white" : "bg-white border border-surface-variant text-outline"}`}>{item.label}</button>)}</div></div></div>
    {loading ? <div className="h-64 flex justify-center items-center"><Loader2 className="animate-spin text-primary" size={32} /></div> : visible.length === 0 ? <div className="py-20 text-center bg-white rounded-2xl border border-surface-variant text-outline"><ClipboardList size={44} className="mx-auto mb-3 opacity-30" /><p>درخواستی پیدا نشد</p></div> : <div className="bg-white rounded-2xl border border-surface-variant overflow-x-auto"><table className="w-full text-sm"><thead className="bg-surface-low text-outline"><tr><th className="text-right p-3">متقاضی</th><th className="text-right p-3">دوره</th><th className="text-right p-3 hidden md:table-cell">تاریخ</th><th className="text-center p-3">وضعیت</th><th className="p-3" /></tr></thead><tbody>{grouped.map(([courseId, courseTitle]) => { const rows = visible.filter((item) => item.course.id === courseId); return (<Fragment key={courseId}><tr className="bg-primary/5"><td colSpan={5} className="px-3 py-2 text-xs font-black text-primary">{courseTitle}<span className="mr-2 text-outline">({rows.length} نفر)</span></td></tr>{rows.map((item) => <tr key={item.id} className="border-t border-surface-variant"><td className="p-3"><p className="font-bold text-primary">{item.fullName}</p><p className="text-xs text-outline mt-1" dir="ltr">{item.phone}</p></td><td className="p-3 text-outline">{item.course.title}</td><td className="p-3 text-outline hidden md:table-cell">{new Date(item.createdAt).toLocaleDateString("fa-IR")}</td><td className="p-3 text-center"><span className={`px-2.5 py-1 rounded-full text-xs font-bold ${item.status === "approved" ? "bg-green-50 text-green-700" : item.status === "rejected" ? "bg-error-container text-error" : "bg-yellow-50 text-yellow-700"}`}>{statusLabels[item.status]}</span></td><td className="p-3"><button onClick={() => setSelected(item)} className="p-2 text-outline hover:text-primary"><Eye size={17} /></button></td></tr>)}</Fragment>); })}</tbody></table></div>}
    {selected && <div className="modal-overlay" onClick={() => !saving && setSelected(null)}><div className="modal-content max-w-3xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between mb-5"><div><p className="text-xs font-bold text-secondary">درخواست ثبت‌نام</p><h2 className="text-xl font-black text-primary mt-1">{selected.course.title}</h2></div><button onClick={() => setSelected(null)} className="p-2 text-outline"><X size={20} /></button></div><div className="grid sm:grid-cols-2 gap-3">{fields.map(([label, value]) => <div key={label} className={`rounded-xl bg-surface-low border border-surface-variant p-3 ${["آدرس", "سوابق کاری", "سوابق هنری", "دلیل انتخاب دوره", "آشنایی قبلی با اساتید"].includes(label) ? "sm:col-span-2" : ""}`}><p className="text-[11px] text-outline">{label}</p><p className="text-sm text-primary mt-1 leading-7 whitespace-pre-line">{value}</p></div>)}</div><div className="flex flex-wrap gap-3 mt-6 pt-5 border-t border-surface-variant"><button onClick={() => changeStatus("approved")} disabled={saving} className="bg-green-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2"><Check size={16} />تأیید و ثبت در دوره</button><button onClick={() => changeStatus("rejected")} disabled={saving} className="bg-error text-white px-5 py-2.5 rounded-xl text-sm font-bold">رد درخواست</button>{selected.status !== "pending" && <button onClick={() => changeStatus("pending")} disabled={saving} className="border border-surface-variant px-5 py-2.5 rounded-xl text-sm text-outline">بازگشت به انتظار</button>}</div></div></div>}
  </div>;
}
