"use client";

import { useState } from "react";
import { CheckCircle2, Loader2, Mail, Send } from "lucide-react";
import { getCookie } from "@/lib/cookie";

export default function EmailComposer() {
  const [form, setForm] = useState({ to: "", senderName: "آکادمی هنر و رسانه امام روح‌الله", senderUsername: "academy", subject: "", message: "" });
  const [loading, setLoading] = useState(false); const [result, setResult] = useState(""); const [error, setError] = useState("");
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); setResult(""); try { const response = await fetch("/api/admin/email", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${getCookie("token") || ""}` }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "ارسال ایمیل انجام نشد"); setResult(data.message); setForm((current) => ({ ...current, to: "", subject: "", message: "" })); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "ارسال ایمیل انجام نشد"); } finally { setLoading(false); } }
  const inputClass = "mt-2 w-full rounded-xl border border-outline-variant bg-surface px-4 py-3 text-sm outline-none transition focus:border-secondary focus:ring-2 focus:ring-secondary/20";
  return <div className="max-w-5xl">
    <div className="mb-8"><p className="text-sm font-bold text-secondary">ارتباط مستقیم</p><h2 className="mt-2 text-3xl font-black text-primary">ارسال ایمیل از دامنه آکادمی</h2><p className="mt-2 text-sm text-outline">پیام را بنویسید؛ سامانه آن را در قالب گرافیکی رسمی آکادمی برای گیرنده ارسال می‌کند.</p></div>
    {result && <div className="mb-5 flex items-center gap-2 rounded-xl bg-green-50 px-4 py-3 text-sm text-green-700"><CheckCircle2 size={18} />{result}</div>}{error && <div className="mb-5 rounded-xl bg-error-container px-4 py-3 text-sm text-error">{error}</div>}
    <form onSubmit={submit} className="grid gap-6 lg:grid-cols-[1fr_.85fr]"><div className="rounded-3xl border border-surface-variant bg-white p-6 shadow-sm md:p-8"><div className="mb-6 flex items-center gap-3 border-b border-surface-variant pb-5"><div className="rounded-2xl bg-secondary-fixed p-3 text-primary"><Mail size={23} /></div><div><h3 className="font-black text-primary">جزئیات پیام</h3><p className="text-xs text-outline">گیرنده و محتوای ایمیل</p></div></div><label className="block text-sm font-bold text-primary">نشانی گیرنده<input required type="email" value={form.to} onChange={(e) => update("to", e.target.value)} className={inputClass} placeholder="recipient@example.com" dir="ltr" /></label><label className="mt-5 block text-sm font-bold text-primary">عنوان پیام<input required value={form.subject} onChange={(e) => update("subject", e.target.value)} className={inputClass} placeholder="عنوان ایمیل" /></label><label className="mt-5 block text-sm font-bold text-primary">متن پیام<textarea required rows={9} value={form.message} onChange={(e) => update("message", e.target.value)} className={`${inputClass} resize-y`} placeholder="متن پیام خود را بنویسید..." /></label><button disabled={loading} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3.5 font-bold text-white transition hover:bg-primary-container disabled:opacity-60">{loading ? <Loader2 size={18} className="animate-spin" /> : <Send size={18} />}ارسال پیام</button></div><div className="rounded-3xl bg-primary p-6 text-white shadow-xl md:p-8"><p className="text-xs font-bold tracking-widest text-secondary-fixed">FROM</p><h3 className="mt-3 text-2xl font-black">هویت ارسال‌کننده</h3><p className="mt-3 text-sm leading-7 text-white/65">نام نمایشی و نام کاربری دامنه را انتخاب کنید. ایمیل با نشانی زیر ارسال خواهد شد:</p><div className="mt-7 rounded-2xl border border-white/10 bg-white/5 p-4 text-center font-mono text-sm text-secondary-fixed" dir="ltr">{form.senderUsername || "academy"}@imamruhollahschool.com</div><label className="mt-7 block text-sm font-bold text-secondary-fixed">نام نمایشی<input required value={form.senderName} onChange={(e) => update("senderName", e.target.value)} className={inputClass} /></label><label className="mt-5 block text-sm font-bold text-secondary-fixed">نام کاربری دامنه<input required value={form.senderUsername} onChange={(e) => update("senderUsername", e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g, ""))} className={`${inputClass} font-mono`} dir="ltr" placeholder="academy" /></label></div></form>
  </div>;
}
