"use client";

import * as XLSX from "xlsx";
import { Download, Printer } from "lucide-react";
import toast from "react-hot-toast";
import { getCookie } from "@/lib/cookie";

const labels: Record<string, string> = { id: "شناسه", status: "وضعیت", fullName: "نام کامل", name: "نام", email: "ایمیل", phone: "موبایل", nationalCode: "کد ملی", course: "دوره", title: "عنوان", orderNumber: "شماره سفارش", amountTomans: "مبلغ (تومان)", amountRials: "مبلغ (ریال)", method: "روش پرداخت", createdAt: "تاریخ ایجاد", updatedAt: "تاریخ بروزرسانی", paidAt: "تاریخ پرداخت", province: "استان", city: "شهر", address: "نشانی", postalCode: "کدپستی", educationLevel: "مقطع تحصیلی", educationField: "رشته تحصیلی", reason: "دلیل انتخاب", workHistory: "سوابق کاری", artHistory: "سوابق هنری", receiptUrl: "رسید پرداخت" };
function flatten(value: unknown, prefix = "", result: Record<string, string | number | boolean> = {}) { if (value === null || value === undefined) { result[prefix] = ""; return result; } if (typeof value !== "object") { result[prefix] = typeof value === "string" && /At$/.test(prefix) ? new Date(value).toLocaleString("fa-IR") : value as string | number | boolean; return result; } Object.entries(value as Record<string, unknown>).forEach(([key, child]) => flatten(child, prefix ? `${prefix}.${key}` : key, result)); return result; }
function header(key: string) { return key.split(".").map((part) => labels[part] || part).join(" - "); }
function escapeHtml(value: unknown) { return String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] || char); }

export default function ExportActions({ endpoint, title, fileName }: { endpoint: string; title: string; fileName: string }) {
  async function records() { const response = await fetch(endpoint, { headers: { Authorization: `Bearer ${getCookie("token") || ""}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "دریافت اطلاعات ناموفق بود"); return data.records || []; }
  async function excel() { try { const rows = (await records()).map((item: unknown) => flatten(item)); const worksheet = XLSX.utils.json_to_sheet(rows); const keys = Object.keys(rows[0] || {}); XLSX.utils.sheet_add_aoa(worksheet, [keys.map(header)], { origin: "A1" }); worksheet["!cols"] = keys.map(() => ({ wch: 24 })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, title); XLSX.writeFile(workbook, `${fileName}.xlsx`); } catch (error) { toast.error(error instanceof Error ? error.message : "ساخت فایل اکسل ناموفق بود"); } }
  async function printReport() { try { const rows = (await records()).map((item: unknown) => flatten(item)); const keys = Object.keys(rows[0] || {}); const popup = window.open("", "_blank"); if (!popup) throw new Error("اجازه باز شدن پنجره گزارش را بدهید"); let printed = false; const printWhenReady = () => { if (printed) return; printed = true; popup.focus(); popup.print(); }; popup.onload = () => window.setTimeout(printWhenReady, 250); popup.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:Tahoma,Arial,sans-serif;color:#16164d;margin:28px}header{border-bottom:3px solid #03004b;padding-bottom:16px;display:flex;justify-content:space-between;align-items:center}h1{margin:0;font-size:22px}p{color:#555}table{width:100%;border-collapse:collapse;margin-top:22px;font-size:11px}th,td{border:1px solid #cfcfe0;padding:7px;text-align:right;vertical-align:top;word-break:break-word}th{background:#03004b;color:white}@media print{body{margin:12px}}</style></head><body><header><div><h1>آکادمی هنر و رسانه امام روح‌الله</h1><p>${title}</p></div><p>تاریخ گزارش: ${new Date().toLocaleString("fa-IR")}</p></header><p>این گزارش برای چاپ و ذخیره با گزینه «Save as PDF» آماده است.</p><table><thead><tr>${keys.map((key) => `<th>${escapeHtml(header(key))}</th>`).join("")}</tr></thead><tbody>${rows.map((row: Record<string, unknown>) => `<tr>${keys.map((key) => `<td>${escapeHtml(row[key])}</td>`).join("")}</tr>`).join("")}</tbody></table></body></html>`); popup.document.close(); window.setTimeout(printWhenReady, 900); } catch (error) { toast.error(error instanceof Error ? error.message : "ساخت گزارش ناموفق بود"); } }
  return <div className="flex flex-wrap gap-2"><button onClick={excel} className="inline-flex items-center gap-2 rounded-xl border border-secondary bg-white px-3 py-2 text-xs font-bold text-secondary"><Download size={16} />خروجی اکسل</button><button onClick={printReport} className="inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-xs font-bold text-white"><Printer size={16} />گزارش قابل چاپ / PDF</button></div>;
}
